deployment:
  tasks:
    - export DEPLOYPATH=/home/administrador/public_html/2026.uneg.edu.mx
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp -R _app $DEPLOYPATH/
    - /bin/cp -R _assets $DEPLOYPATH/
    - /bin/cp -R _imgs $DEPLOYPATH/
