<?php
return [
  [
    'title' => 'Comunicado institucional de Rectoría',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Información oficial y anuncios institucionales para la comunidad ISEC.',
    'href' => '/comunidad/noticias/comunicados-de-rectoria',
    'category' => 'comunicados-de-rectoria',
    'image' => '/imgs/noticias/comunicados/news-001.jpg',
  ],
  [
    'title' => 'Evento de nuestra comunidad',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Universidad de Negocios ISEC firma convenio con la Cámara Árabe Mexicana de Industria y Comercio.',
    'href' => '/comunidad/noticias/eventos-de-nuestra-comunidad/firma-convenio-camic',
    'category' => 'eventos-de-nuestra-comunidad',
    'image' => '/imgs/noticias/eventos/news-001.jpg',
  ],
  [
    'title' => 'Vida en el campus: actividades culturales',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Momentos y experiencias dentro de ISEC.',
    'href' => '/comunidad/noticias/vida-en-el-campus',
    'category' => 'vida-en-el-campus',
    'image' => '/imgs/noticias/campus/news-001.jpg',
  ],
  [
    'title' => 'Videotutorial de uso Microsoft Teams como herramienta para tomar clases en línea',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Videotutorial para el uso de Microsoft Teams en clases en línea.',
    'href' => '/comunidad/noticias/video-blog-uneg-isec/videotutorial-microsoft-teams',
    'category' => 'video-blog-uneg-isec',
    'video_url' => 'https://youtu.be/hLtWWbKNwKc',
  ],
  [
    'title' => 'Licenciatura en Innovación Turística y Gastronómica',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Conoce la Licenciatura en Innovación Turística y Gastronómica.',
    'href' => '/comunidad/noticias/video-blog-uneg-isec/licenciatura-innovacion-turistica-gastronomica',
    'category' => 'video-blog-uneg-isec',
    'video_url' => 'https://youtu.be/NejQkYJ8y3Q',
  ],
  [
    'title' => 'Licenciatura en Psicología',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Conoce la Licenciatura en Psicología.',
    'href' => '/comunidad/noticias/video-blog-uneg-isec/licenciatura-psicologia',
    'category' => 'video-blog-uneg-isec',
    'video_url' => 'https://youtu.be/EkrNWgVh-XY',
  ],
  [
    'title' => 'Licenciatura en Ing. en Tecnologías de Información para Negocios',
    'date' => '11 febrero, 2026',
    'excerpt' => 'Conoce la Licenciatura en Ing. en Tecnologías de Información para Negocios.',
    'href' => '/comunidad/noticias/video-blog-uneg-isec/licenciatura-ti-para-negocios',
    'category' => 'video-blog-uneg-isec',
    'video_url' => 'https://youtu.be/iromNmTZpWk',
  ],
];
