<?php
$title = 'Gracias | UNEG';
$active = '';
require __DIR__ . '/partials/header-lp.php';

$origen = trim((string) ($_GET['origen'] ?? ''));
$esBuzon = $origen === 'buzon';
$tituloGracias = $esBuzon ? 'Gracias por escribir al Buzón del Rector' : 'Gracias por contactarnos';
$mensajeGracias = $esBuzon
  ? 'Tu solicitud fue enviada correctamente. Será atendida y revisada por el equipo de Rectoría en breve.'
  : 'Hemos recibido tu información. Un asesor se pondrá en contacto contigo lo antes posible.';
?>

<main class="mx-auto flex min-h-[calc(100vh-220px)] max-w-3xl items-center px-4 py-12">
  <section class="w-full rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm sm:p-10">
    <div class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#0b2c65] text-white">
      <i class="text-3xl" data-lucide="check-circle"></i>
    </div>
    <h1 class="mt-4 text-2xl sm:text-3xl font-semibold text-[#0b2c65]"><?php echo htmlspecialchars($tituloGracias, ENT_QUOTES, 'UTF-8'); ?></h1>
    <p class="mx-auto mt-3 max-w-2xl text-slate-600">
      <?php echo htmlspecialchars($mensajeGracias, ENT_QUOTES, 'UTF-8'); ?>
    </p>
    <div class="mt-6 flex flex-wrap justify-center gap-3">
      <a class="rounded-md bg-[#0b2c65] px-6 py-2.5 text-white font-semibold shadow-sm hover:bg-[#09306e]" href="<?php echo $base; ?>/oferta-educativa">Ver oferta educativa</a>
      <a class="rounded-md border border-slate-300 px-6 py-2.5 text-slate-700 font-semibold hover:border-slate-400" href="<?php echo $base; ?>/">Ir al inicio</a>
    </div>
  </section>
</main>

<?php if (!$esBuzon): ?>
  <!-- SPOTIFY EVENTO DE CONVERSION (SOLO GRACIAS LP) -->
  <script>
    // Installation script generated by Spotify Ads Manager
    (function(w, d){
      var id='spdt-capture', n='script';
      if (!d.getElementById(id)) {
        w.spdt =
          w.spdt ||
          function() {
            (w.spdt.q = w.spdt.q || []).push(arguments);
          };
        var e = d.createElement(n); e.id = id; e.async=1;
        e.src = 'https://pixel.byspotify.com/ping.min.js';
        var s = d.getElementsByTagName(n)[0];
        s.parentNode.insertBefore(e, s);
      }

      w.spdt('conf', { key: '14c182851580462a8db1af7fa7e8491c' });
      w.spdt('lead');
      w.spdt('custom_event_2');

    })(window, document);
  </script>
  <!-- /SPOTIFY EVENTO DE CONVERSION (SOLO GRACIAS LP) -->
  <script>
    gtag('event', 'conversion', {
      'send_to': 'AW-17972441356/n6SkCJLK2f0bEIzi9vlC',
      'value': 1.0,
      'currency': 'MXN'
    });
  </script>
<?php endif; ?>

<?php require __DIR__ . '/partials/footer.php'; ?>
